name:                LTLplanSAT
version:             0.1.0.0
github:              "githubuser/LTLplanSAT"
license:             "GPL-3.0-or-later"
author:              "Amos Nicodemus"
maintainer:          "nicodemusamos@gmail.com"
copyright:           "2024 Amos Nicodemus"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/AmosNico/LTLplanSAT#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10
- containers >= 0.6
- process >= 1.6
- vector >= 0.12

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  LTLplanSAT-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LTLplanSAT

tests:
  LTLplanSAT-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LTLplanSAT