name:                LTLplanSAT
version:             0.1.0.0
github:              "githubuser/LTLplanSAT"
license:             "GPL-3.0-or-later"
author:              "Amos Nicodemus"
maintainer:          "nicodemusamos@gmail.com"
copyright:           "2024 Amos Nicodemus"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/AmosNico/LTLplanSAT#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.11.5.3
- process >= 1.6.19.0
- vector >= 0.13.1.0
- containers >= 0.6.7
- megaparsec
- mtl >= 2.3.1
- ersatz
- ghc >= 9.6.5
- random >= 1.2.1.2
- extra >= 1.7.16
- optparse-applicative
- word8 >= 0.1.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  LTLplanSAT:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LTLplanSAT

tests:
  LTLplanSAT-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LTLplanSAT