resolver:   
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/24.yaml
# resolver: lts-20.17
packages:
- .

# flags: {}
# extra-package-dbs: []
local-bin-path: .